import { IPC_CHANNELS } from '@megumi/shared/ipc-channels';
import type { BusinessIpcChannel } from '@megumi/shared/ipc-contracts';

export function rendererRuntimeOperationNameFromChannel(channel: BusinessIpcChannel): string {
  switch (channel) {
    case IPC_CHANNELS.provider.list:
      return 'provider.list';
    case IPC_CHANNELS.provider.update:
      return 'provider.update';
    case IPC_CHANNELS.provider.setApiKey:
      return 'provider.set-api-key';
    case IPC_CHANNELS.provider.deleteApiKey:
      return 'provider.delete-api-key';
    case IPC_CHANNELS.session.create:
      return 'session.create';
    case IPC_CHANNELS.session.list:
      return 'session.list';
    case IPC_CHANNELS.session.message.send:
      return 'session.message.send';
    case IPC_CHANNELS.session.message.cancel:
      return 'session.message.cancel';
    case IPC_CHANNELS.run.events.list:
      return 'run.events.list';
    case IPC_CHANNELS.runContext.baselineGet:
      return 'run-context.baseline.get';
    case IPC_CHANNELS.runContext.sourcesList:
      return 'run-context.sources.list';
    case IPC_CHANNELS.plan.byRunGet:
      return 'plan.by-run.get';
    case IPC_CHANNELS.plan.statusUpdate:
      return 'plan.status.update';
    case IPC_CHANNELS.tool.definitionsList:
      return 'tool.definitions.list';
    case IPC_CHANNELS.tool.callGet:
      return 'tool.call.get';
    case IPC_CHANNELS.approval.resolve:
      return 'approval.resolve';
    case IPC_CHANNELS.recovery.recoverableRunsList:
      return 'recovery.recoverable-runs.list';
    case IPC_CHANNELS.recovery.resume:
      return 'recovery.resume';
    case IPC_CHANNELS.recovery.cancel:
      return 'recovery.cancel';
    case IPC_CHANNELS.recovery.retry:
      return 'recovery.retry';
    case IPC_CHANNELS.artifacts.listByRun:
      return 'artifacts.list-by-run';
    case IPC_CHANNELS.artifacts.listBySession:
      return 'artifacts.list-by-session';
    case IPC_CHANNELS.artifacts.get:
      return 'artifacts.get';
    case IPC_CHANNELS.artifacts.versionGet:
      return 'artifacts.version.get';
    case IPC_CHANNELS.artifacts.versionCreate:
      return 'artifacts.version.create';
    case IPC_CHANNELS.artifacts.statusUpdate:
      return 'artifacts.status.update';
    case IPC_CHANNELS.artifacts.reference:
      return 'artifacts.reference';
    case IPC_CHANNELS.memory.settingsGet:
      return 'memory.settings.get';
    case IPC_CHANNELS.memory.settingsUpdate:
      return 'memory.settings.update';
    case IPC_CHANNELS.memory.candidateList:
      return 'memory.candidate.list';
    case IPC_CHANNELS.memory.candidateAccept:
      return 'memory.candidate.accept';
    case IPC_CHANNELS.memory.candidateReject:
      return 'memory.candidate.reject';
    case IPC_CHANNELS.memory.candidateArchive:
      return 'memory.candidate.archive';
    case IPC_CHANNELS.memory.candidateEditAndAccept:
      return 'memory.candidate.edit-and-accept';
    case IPC_CHANNELS.memory.memoryList:
      return 'memory.memory.list';
    case IPC_CHANNELS.memory.memoryGet:
      return 'memory.memory.get';
    case IPC_CHANNELS.memory.memoryUpdate:
      return 'memory.memory.update';
    case IPC_CHANNELS.memory.memoryArchive:
      return 'memory.memory.archive';
    case IPC_CHANNELS.memory.memoryDelete:
      return 'memory.memory.delete';
    case IPC_CHANNELS.memory.memoryDisable:
      return 'memory.memory.disable';
    case IPC_CHANNELS.memory.memoryEnable:
      return 'memory.memory.enable';
    case IPC_CHANNELS.memory.sourceRefsList:
      return 'memory.source-refs.list';
    case IPC_CHANNELS.memory.accessLogsList:
      return 'memory.access-logs.list';
    case IPC_CHANNELS.memory.recallPreview:
      return 'memory.recall-preview';
    case IPC_CHANNELS.agent.session.create:
      return 'agent.session.create';
    case IPC_CHANNELS.agent.session.list:
      return 'agent.session.list';
    case IPC_CHANNELS.agent.run.start:
      return 'agent.run.start';
    case IPC_CHANNELS.agent.context.baselineGet:
      return 'agent.context.baseline.get';
    case IPC_CHANNELS.agent.context.sourcesList:
      return 'agent.context.sources.list';
    case IPC_CHANNELS.agent.plan.byRunGet:
      return 'agent.plan.by-run.get';
    case IPC_CHANNELS.agent.plan.statusUpdate:
      return 'agent.plan.status.update';
    case IPC_CHANNELS.agent.tool.definitionsList:
      return 'agent.tool.definitions.list';
    case IPC_CHANNELS.agent.tool.callGet:
      return 'agent.tool.call.get';
    case IPC_CHANNELS.agent.approval.resolve:
      return 'agent.approval.resolve';
    case IPC_CHANNELS.agent.recovery.recoverableRunsList:
      return 'agent.recovery.recoverable-runs.list';
    case IPC_CHANNELS.agent.recovery.resume:
      return 'agent.recovery.resume';
    case IPC_CHANNELS.agent.recovery.cancel:
      return 'agent.recovery.cancel';
    case IPC_CHANNELS.agent.recovery.retry:
      return 'agent.recovery.retry';
    case IPC_CHANNELS.agent.artifacts.listByRun:
      return 'agent.artifacts.list-by-run';
    case IPC_CHANNELS.agent.artifacts.listBySession:
      return 'agent.artifacts.list-by-session';
    case IPC_CHANNELS.agent.artifacts.get:
      return 'agent.artifacts.get';
    case IPC_CHANNELS.agent.artifacts.versionGet:
      return 'agent.artifacts.version.get';
    case IPC_CHANNELS.agent.artifacts.versionCreate:
      return 'agent.artifacts.version.create';
    case IPC_CHANNELS.agent.artifacts.statusUpdate:
      return 'agent.artifacts.status.update';
    case IPC_CHANNELS.agent.artifacts.reference:
      return 'agent.artifacts.reference';
    case IPC_CHANNELS.agent.memory.settingsGet:
      return 'agent.memory.settings.get';
    case IPC_CHANNELS.agent.memory.settingsUpdate:
      return 'agent.memory.settings.update';
    case IPC_CHANNELS.agent.memory.candidateList:
      return 'agent.memory.candidate.list';
    case IPC_CHANNELS.agent.memory.candidateAccept:
      return 'agent.memory.candidate.accept';
    case IPC_CHANNELS.agent.memory.candidateReject:
      return 'agent.memory.candidate.reject';
    case IPC_CHANNELS.agent.memory.candidateArchive:
      return 'agent.memory.candidate.archive';
    case IPC_CHANNELS.agent.memory.candidateEditAndAccept:
      return 'agent.memory.candidate.edit-and-accept';
    case IPC_CHANNELS.agent.memory.memoryList:
      return 'agent.memory.memory.list';
    case IPC_CHANNELS.agent.memory.memoryGet:
      return 'agent.memory.memory.get';
    case IPC_CHANNELS.agent.memory.memoryUpdate:
      return 'agent.memory.memory.update';
    case IPC_CHANNELS.agent.memory.memoryArchive:
      return 'agent.memory.memory.archive';
    case IPC_CHANNELS.agent.memory.memoryDelete:
      return 'agent.memory.memory.delete';
    case IPC_CHANNELS.agent.memory.memoryDisable:
      return 'agent.memory.memory.disable';
    case IPC_CHANNELS.agent.memory.memoryEnable:
      return 'agent.memory.memory.enable';
    case IPC_CHANNELS.agent.memory.sourceRefsList:
      return 'agent.memory.source-refs.list';
    case IPC_CHANNELS.agent.memory.accessLogsList:
      return 'agent.memory.access-logs.list';
    case IPC_CHANNELS.agent.memory.recallPreview:
      return 'agent.memory.recall-preview';
    default:
      return channel.replaceAll(':', '.');
  }
}
