/*
 * Renderer-safe public Product Host Interface exports.
 * Host factory implementations remain internal to Product Composition.
 */
import type { RuntimeEvent } from '@megumi/events';
import { createRuntimeTimeline, reduceRuntimeTimeline } from '@megumi/projections';

export {
  RuntimeContextSchema,
  RuntimeErrorSchema,
  RuntimeEventSchema,
  RuntimeIdSchema,
  RuntimeResultMetaSchema,
  createRuntimeContext as buildRuntimeContext,
  createRuntimeDebugId as generateRuntimeDebugId,
  createRuntimeTraceId as generateRuntimeTraceId,
  normalizeRuntimeError as normalizeHostRuntimeError,
} from '@megumi/events';
export { redactHostRuntimeValue } from './runtime-redaction';
export type {
  AgentRunToolResultCreatedPayload,
  RunCancelledPayload,
  RunFailedPayload,
  RuntimeContext,
  RuntimeError,
  RuntimeEvent,
  ToolCallCompletedPayload,
  ToolCallFailedPayload,
  ToolCallRequestedPayload,
  ToolCallStartedPayload,
} from '@megumi/events';
export { TimelineMessageSchema } from '@megumi/projections';
export type {
  AnswerTextBlock,
  AssistantTextItem,
  BranchSeparatorBlock,
  CancelledActivityItem,
  CompactionActivityItem,
  ErrorActivityItem,
  PlanActivityItem,
  ProcessDisclosureBlock,
  ProcessDisclosureItem,
  RecoveryActivityItem,
  RetryActivityItem,
  ThinkingItem,
  TimelineAssistantMessage,
  TimelineMessage,
  TimelineUserMessage,
  ToolActivityItem,
  UserTimelineBlock,
  WorkspaceChangeFooterFile,
  WorkspaceChangeFooterFact,
} from '@megumi/projections';

export function reduceRuntimeTimelineEvent(
  messages: import('@megumi/projections').TimelineMessage[],
  event: RuntimeEvent,
): import('@megumi/projections').TimelineMessage[] {
  return reduceRuntimeTimeline({
    timeline: createRuntimeTimeline({ messages }),
    event,
  }).messages;
}


export * from './product-host';
export type {
  DirectoryPickerPort,
  FileOpenPort,
  WorkspaceFileEntryUiDto,
  WorkspaceListFilesUiResult,
  WorkspaceListProjectsUiResult,
  WorkspaceOpenFileUiResult,
  WorkspaceOpenProjectUiResult,
  WorkspaceProjectUiDto,
  WorkspaceRemoveProjectUiResult,
  WorkspaceUseExistingProjectUiResult,
} from './workspace-contract';
export type { WorkspaceHost } from './workspace-host';
export type {
  ChatCancelBranchDraftUiResult,
  ChatCancelUserInputUiResult,
  ChatCancelUserInputUiPayload,
  ChatCreateBranchDraftUiResult,
  ChatCreateSessionUiResult,
  ChatGetCommandSuggestionsUiResult,
  ChatGetContextUsageUiResult,
  ChatGetSessionHydrationUiResult,
  ChatHost,
  ChatListMessagesUiResult,
  ChatListRunEventsUiResult,
  ChatListRunsUiResult,
  ChatListSessionsUiResult,
  ChatListTimelineUiResult,
  ChatRunUiDto,
  ChatSendUserInputUiPayload,
  ChatSendUserInputUiResult,
  ChatSessionUiDto,
  CommandSuggestionItem,
  CommandSuggestionResult,
  PermissionMode,
  InputAttachmentPickerPort,
  LocalFileAvailabilityPort,
  SelectedImageUiDto,
  SelectedDocumentUiDto,
  ChatImageInputCapabilitiesUiResult,
  ChatSelectImagesUiResult,
  ChatSelectDocumentsUiResult,
  ChatReadAttachmentImageUiRequest,
  ChatReadAttachmentImageUiResult,
  ChatGetAttachmentFileStatusUiRequest,
  ChatGetAttachmentFileStatusUiResult,
} from './chat-contract';
export type {
  DisableSkillUiResponse,
  DeleteSkillUiResponse,
  EnableSkillUiResponse,
  GetSkillDetailUiResponse,
  ListSkillsUiResponse,
  SkillDetailUiDto,
  SkillHost,
  SkillListUiItem,
} from './skills-host';
export type {
  AppLanguage,
  AppThemeName,
  EmptyUiResult,
  ModelCapabilitiesUiDto,
  ModelSupportLevelUi,
  ProviderModelSettingsUiDto,
  ProviderCatalogUiDto,
  ProviderListUiResult,
  ProviderPublicStatusUiDto,
  PermissionRuleEffectUi,
  PermissionRuleUiDto,
  PermissionRuleChangeUi,
  PermissionRuleCatalogUiDto,
  SettingsCompleteSetupUiResult,
  SettingsCompleteSetupPayload,
  SettingsData,
  SettingsGetPayload,
  SettingsGetUiResult,
  SettingsUiResolved,
  SettingsUpdatePayload,
  SettingsUpdateUiResult,
} from './settings-contract';
export type { SettingsHost } from './settings-host';
export type {
  ApprovalHost,
  ApprovalHostResult,
  ApprovalResolvePayload,
} from './approval-host';
export type {
  ArtifactGetData,
  ArtifactHost,
  ArtifactListData,
  ArtifactCreateVersionPayload,
  ArtifactReferencePayload,
  ArtifactReferenceData,
  ArtifactStatusUpdatePayload,
  ArtifactStatusUpdateData,
  ArtifactVersionCreateData,
  ArtifactVersionGetData,
} from './artifact-host';
export type { ObservabilityHost, DiagnosticBundleSavePort } from './observability-host';
export type {
  DiagnosticBundleDto,
  DiagnosticBundleFileDto,
  ObservabilityAttributesUiDto,
  ObservabilityExportResult,
  ObservabilityGetRunTraceUiResult,
  ObservabilityListRunTracesUiResult,
  ObservabilityRunTraceDetailUiDto,
  ObservabilityRunTraceSummaryUiDto,
} from './observability-contract';
export { ObservabilityListPayloadSchema, ObservabilityRunPayloadSchema, ObservabilityQueryResultSchema } from './observability-host';
export {
  WorkspaceListProjectsPayloadSchema,
  WorkspaceUseExistingProjectPayloadSchema,
  ProjectOpenPayloadSchema,
  ProjectRemovePayloadSchema,
  WorkspaceFilesListPayloadSchema,
  WorkspaceFileOpenPayloadSchema,
  WorkspaceListProjectsUiResultSchema,
  WorkspaceUseExistingProjectUiResultSchema,
  WorkspaceOpenProjectUiResultSchema,
  WorkspaceRemoveProjectUiResultSchema,
  WorkspaceListFilesUiResultSchema,
  WorkspaceOpenFileUiResultSchema,
} from './workspace-contract';
export {
  CommandSuggestionsPayloadSchema,
  SessionCreatePayloadSchema,
  SessionListPayloadSchema,
  SessionMessageListPayloadSchema,
  SessionTimelineListPayloadSchema,
  SessionHydrationGetPayloadSchema,
  SessionContextUsageGetPayloadSchema,
  SessionMessageSendPayloadSchema,
  SessionMessageCancelPayloadSchema,
  SessionBranchDraftCreatePayloadSchema,
  SessionBranchDraftCancelPayloadSchema,
  RunListBySessionPayloadSchema,
  RunEventsListPayloadSchema,
  ImageInputCapabilitiesPayloadSchema,
  ImageInputSelectPayloadSchema,
  DocumentInputSelectPayloadSchema,
  ImageInputClipboardReadPayloadSchema,
  AttachmentImageReadPayloadSchema,
  AttachmentFileStatusPayloadSchema,
  ChatImageInputCapabilitiesUiResultSchema,
  ChatSelectImagesUiResultSchema,
  ChatSelectDocumentsUiResultSchema,
  ChatReadAttachmentImageUiResultSchema,
  ChatGetAttachmentFileStatusUiResultSchema,
  ChatSendUserInputUiPayloadSchema,
  ChatCommandSuggestionsUiResultSchema,
  ChatCreateSessionUiResultSchema,
  ChatListSessionsUiResultSchema,
  ChatListMessagesUiResultSchema,
  ChatListTimelineUiResultSchema,
  ChatGetSessionHydrationUiResultSchema,
  ChatCancelUserInputUiPayloadSchema,
  ChatCreateBranchDraftUiPayloadSchema,
  ChatCancelBranchDraftUiPayloadSchema,
  ChatListRunsUiResultSchema,
  ChatListRunEventsUiResultSchema,
  ChatGetContextUsageUiResultSchema,
} from './chat-contract';
export {
  SkillListPayloadSchema,
  SkillGetPayloadSchema,
  SkillEnablePayloadSchema,
  SkillDisablePayloadSchema,
  SkillDeletePayloadSchema,
  ListSkillsUiResponseSchema,
  GetSkillDetailUiResponseSchema,
  EnableSkillUiResponseSchema,
  DisableSkillUiResponseSchema,
  DeleteSkillUiResponseSchema,
} from './skills-host';
export {
  SettingsGetPayloadSchema,
  SettingsUpdatePayloadSchema,
  SettingsCompleteSetupPayloadSchema,
  ProviderListPayloadSchema,
  ProviderUpdatePayloadSchema,
  ProviderDeletePayloadSchema,
  ProviderApiKeyPayloadSchema,
  ProviderDeleteApiKeyPayloadSchema,
  SettingsGetUiResultSchema,
  SettingsUpdateUiResultSchema,
  SettingsCompleteSetupUiResultSchema,
  ProviderListUiResultSchema,
  EmptyUiResultSchema,
} from './settings-contract';
export { ApprovalResolvePayloadSchema, ApprovalResolveResultSchema } from './approval-host';
export {
  ArtifactListByRunPayloadSchema,
  ArtifactListBySessionPayloadSchema,
  ArtifactGetPayloadSchema,
  ArtifactVersionGetPayloadSchema,
  ArtifactVersionCreatePayloadSchema,
  ArtifactStatusUpdatePayloadSchema,
  ArtifactReferencePayloadSchema,
  ArtifactListDataSchema,
  ArtifactGetDataSchema,
  ArtifactVersionGetDataSchema,
  ArtifactVersionCreateDataSchema,
  ArtifactStatusUpdateDataSchema,
  ArtifactReferenceDataSchema,
} from './artifact-host';
