/*
 * Renderer-safe public Product Host Interface exports.
 * Host factory implementations remain internal to Product Composition.
 */
export { EventSchema as RuntimeEventSchema } from '@megumi/events';
export { redactHostRuntimeValue } from './runtime-redaction';
export type { AnyEvent } from '@megumi/events';

export * from './product-host';
export type {
  WorkspaceFileEntryUiDto,
  WorkspaceListFilesUiResult,
  WorkspaceListProjectsUiResult,
  WorkspaceOpenFileUiResult,
  WorkspaceOpenProjectUiResult,
  WorkspaceProjectUiDto,
  WorkspaceRemoveProjectUiResult,
  WorkspaceUseExistingProjectUiResult,
} from './workspace-host';
export type { WorkspaceHost } from './workspace-host';
export type { DirectoryPicker, DirectoryPickerResult } from './capabilities/directory-picker';
export type { FileOpener, FileOpenResult } from './capabilities/file-opener';
export type {
  CancelBranchDraftResult,
  CancelUserInputResult,
  CancelUserInputPayload,
  CreateBranchDraftResult,
  CreateSessionResult,
  GetInputSuggestionsResult,
  GetContextUsageResult,
  ReadSessionRequest,
  ReadSessionResult,
  ReadCommittedRunRequest,
  ReadCommittedRunResult,
  SessionHost,
  ListUserMessagesByRunIdsResult,
  ListSessionsResult,
  RunDto,
  SendUserInputPayload,
  SendUserInputResult,
  SessionDto,
  SessionConversationItemDto,
  SessionMessageConversationItemDto,
  SessionMessageDto,
  SessionBranchConversationItemDto,
  UserMessageDto,
  WorkspaceChangeSummaryDto,
  SessionReadDiagnosticDto,
  SessionRuntimeEventRangeDto,
  InputSuggestionQueryItem,
  InputSuggestionQueryResult,
  PermissionMode,
  SelectedImageDto,
  SelectedDocumentDto,
  InputCapabilitiesResult,
  SelectImagesResult,
  SelectDocumentsResult,
  ReadAttachmentImageRequest,
  ReadAttachmentImageResult,
  GetAttachmentFileStatusRequest,
  GetAttachmentFileStatusResult,
} from './session-host';
export type { AttachmentPicker } from './capabilities/attachment-picker';
export type { LocalFileAvailability } from './capabilities/local-file-availability';
export type {
  DisableSkillUiResponse,
  DeleteSkillUiResponse,
  EnableSkillUiResponse,
  GetSkillDetailUiResponse,
  ListSkillsUiResponse,
  RefreshSkillsUiResponse,
  SkillDetailUiDto,
  SkillHost,
  SkillListUiItem,
} from './skill-host';
export type {
  AppLanguage,
  AppThemeName,
  EmptyUiResult,
  ModelCapabilitiesUiDto,
  ModelSupportLevelUi,
  ProviderModelSettingsUiDto,
  ProviderCatalogUiDto,
  ProviderListUiResult,
  ProviderPublicStatusUiDto,
  PermissionRuleEffectUi,
  PermissionRuleUiDto,
  PermissionRuleChangeUi,
  PermissionRuleCatalogUiDto,
  SettingsCompleteSetupUiResult,
  SettingsCompleteSetupPayload,
  SettingsData,
  SettingsGetPayload,
  SettingsGetUiResult,
  SettingsUiResolved,
  SettingsUpdatePayload,
  SettingsUpdateUiResult,
} from './settings-host';
export type { SettingsHost } from './settings-host';
export type {
  ApprovalHost,
  ApprovalHostResult,
  ApprovalResolvePayload,
} from './approval-host';
export type { ObservabilityHost } from './observability-host';
export type { DiagnosticBundleSaver } from './capabilities/diagnostic-bundle-saver';
export type {
  DiagnosticBundleDto,
  DiagnosticBundleFileDto,
  ObservabilityAttributesUiDto,
  ObservabilityExportResult,
  ObservabilityGetRunTraceUiResult,
  ObservabilityListRunTracesUiResult,
  ObservabilityRunTraceDetailUiDto,
  ObservabilityRunTraceSummaryUiDto,
} from './observability-host';
export { ObservabilityListPayloadSchema, ObservabilityRunPayloadSchema, ObservabilityQueryResultSchema } from './observability-host';
export {
  WorkspaceListProjectsPayloadSchema,
  WorkspaceUseExistingProjectPayloadSchema,
  ProjectOpenPayloadSchema,
  ProjectRemovePayloadSchema,
  WorkspaceFilesListPayloadSchema,
  WorkspaceFileOpenPayloadSchema,
  WorkspaceListProjectsUiResultSchema,
  WorkspaceUseExistingProjectUiResultSchema,
  WorkspaceOpenProjectUiResultSchema,
  WorkspaceRemoveProjectUiResultSchema,
  WorkspaceListFilesUiResultSchema,
  WorkspaceOpenFileUiResultSchema,
} from './workspace-host';
export {
  InputSuggestionsPayloadSchema,
  SessionCreatePayloadSchema,
  SessionListPayloadSchema,
  SessionMessageListPayloadSchema,
  SessionReadPayloadSchema,
  CommittedRunReadPayloadSchema,
  SessionContextUsageGetPayloadSchema,
  SessionMessageSendPayloadSchema,
  SessionMessageCancelPayloadSchema,
  SessionBranchDraftCreatePayloadSchema,
  SessionBranchDraftCancelPayloadSchema,
  InputCapabilitiesPayloadSchema,
  ImageInputSelectPayloadSchema,
  DocumentInputSelectPayloadSchema,
  ImageInputClipboardReadPayloadSchema,
  AttachmentImageReadPayloadSchema,
  AttachmentFileStatusPayloadSchema,
  InputCapabilitiesResultSchema,
  SelectImagesResultSchema,
  SelectDocumentsResultSchema,
  ReadAttachmentImageResultSchema,
  AttachmentFileStatusResultSchema,
  SendUserInputPayloadSchema,
  GetInputSuggestionsResultSchema,
  CreateSessionResultSchema,
  ListSessionsResultSchema,
  ListUserMessagesByRunIdsResultSchema,
  CancelUserInputPayloadSchema,
  CreateBranchDraftPayloadSchema,
  CancelBranchDraftPayloadSchema,
  GetContextUsageResultSchema,
  ReadSessionResultSchema,
  ReadCommittedRunResultSchema,
  SessionDtoSchema,
  RunDtoSchema,
  UserMessageDtoSchema,
  SessionMessageDtoSchema,
  SessionMessageConversationItemDtoSchema,
  SessionConversationItemDtoSchema,
  SessionBranchConversationItemDtoSchema,
  WorkspaceChangeSummaryDtoSchema,
} from './session-host';
export {
  SkillListPayloadSchema,
  SkillGetPayloadSchema,
  SkillEnablePayloadSchema,
  SkillDisablePayloadSchema,
  SkillDeletePayloadSchema,
  SkillRefreshPayloadSchema,
  ListSkillsUiResponseSchema,
  GetSkillDetailUiResponseSchema,
  EnableSkillUiResponseSchema,
  DisableSkillUiResponseSchema,
  DeleteSkillUiResponseSchema,
  RefreshSkillsUiResponseSchema,
} from './skill-host';
export {
  SettingsGetPayloadSchema,
  SettingsUpdatePayloadSchema,
  SettingsCompleteSetupPayloadSchema,
  ProviderListPayloadSchema,
  ProviderUpdatePayloadSchema,
  ProviderDeletePayloadSchema,
  ProviderApiKeyPayloadSchema,
  ProviderDeleteApiKeyPayloadSchema,
  SettingsGetUiResultSchema,
  SettingsUpdateUiResultSchema,
  SettingsCompleteSetupUiResultSchema,
  ProviderListUiResultSchema,
  EmptyUiResultSchema,
} from './settings-host';
export { ApprovalResolvePayloadSchema, ApprovalResolveResultSchema } from './approval-host';
