/*
 * Electron IPC channel names owned by the desktop shell.
 */
export const IPC_CHANNELS = {
  settingsRecovery: {
    get: 'settings-recovery:get',
    openDirectory: 'settings-recovery:open-directory',
    restart: 'settings-recovery:restart',
  },
  window: {
    minimize: 'window:minimize',
    toggleMaximize: 'window:toggle-maximize',
    close: 'window:close',
  },
  applicationUpdate: {
    snapshotGet: 'application-update:snapshot:get',
    check: 'application-update:check',
    automaticChecksSet: 'application-update:automatic-checks:set',
    download: 'application-update:download',
    restartAndInstall: 'application-update:restart-and-install',
    releasePageOpen: 'application-update:release-page:open',
    snapshotChanged: 'application-update:snapshot:changed',
  },
  settings: {
    read: 'settings:read',
    update: 'settings:update',
    changed: 'settings:changed',
  },
  credentials: { read: 'credentials:read', update: 'credentials:update' },
  models: { getCatalog: 'models:get-catalog' },
  tools: { list: 'tools:list' },
  session: {
    inputSuggestions: 'input:suggestions',
    sessionCreate: 'session:create',
    sessionModelSelection: 'session:model-selection:update',
    sessionList: 'session:list',
    sessionMessageList: 'session:message:list',
    sessionMessageSend: 'session:message:send',
    sessionMessagePresentation: 'session:message:presentation',
    sessionMessageCancel: 'session:message:cancel',
    sessionRead: 'session:read',
    committedRunRead: 'session:run:read-committed',
    sessionContextUsageGet: 'session:context-usage:get',
    inputCapabilitiesGet: 'image-input:capabilities:get',
    imageInputSelect: 'image-input:select',
    documentInputSelect: 'document-input:select',
    imageInputClipboardRead: 'image-input:clipboard:read',
    attachmentImageRead: 'attachment:image:read',
    attachmentFileStatus: 'attachment:file:status',
    branchDraftCreate: 'session:branch-draft:create',
    branchDraftCancel: 'session:branch-draft:cancel',
  },
  skill: {
    list: 'skill:list',
    get: 'skill:get',
    enable: 'skill:enable',
    disable: 'skill:disable',
    delete: 'skill:delete',
    refresh: 'skill:refresh',
  },
  approval: {
    resolve: 'approval:resolve',
  },
  discovery: {
    interestList: 'discovery:interest:list',
    interestChange: 'discovery:interest:change',
    configurationGet: 'discovery:configuration:get',
    configurationUpdate: 'discovery:configuration:update',
    candidateSupplyConfirm: 'discovery:candidate-supply:confirm',
  },
  voice: {
    snapshot: 'voice:snapshot',
    modelStatus: 'voice:model-status',
    modelCapability: 'voice:model:capability',
    modelsCheckUpdates: 'voice:models:check-updates',
    modelsPrepare: 'voice:models:prepare',
    modelsCancel: 'voice:models:cancel',
    sessionStart: 'voice:session:start',
    sessionManualStart: 'voice:session:manual-start',
    sessionManualFinish: 'voice:session:manual-finish',
    sessionMute: 'voice:session:mute',
    sessionEnd: 'voice:session:end',
    speechOutputStop: 'voice:speech-output:stop',
    speechOutputEvent: 'voice:speech-output:event',
    inputPort: 'voice:input:port',
    inputEvent: 'voice:input:event',
  },
  character: {
    show: 'character:show',
    hide: 'character:hide',
    snapshot: 'character:snapshot',
    snapshotChanged: 'character:snapshot:changed',
    toggleAlwaysOnTop: 'character:always-on-top:toggle',
    setScale: 'character:scale:set',
    setShape: 'character:shape:set',
    moveTo: 'character:position:set',
    openSettings: 'character:settings:open',
    showMainWindow: 'character:main-window:show',
    settingsRequested: 'character:settings:requested',
    selectSession: 'character:session:select',
  },
  workspace: {
    projectList: 'project:list',
    projectUseExisting: 'project:use-existing',
    projectOpen: 'project:open',
    projectRemove: 'project:remove',
    filesList: 'workspace:files:list',
    filesOpen: 'workspace:files:open',
  },
  observability: {
    list: 'observability:list',
    get: 'observability:get',
    content: 'observability:content',
    health: 'observability:health',
    rebuildIndex: 'observability:rebuild-index',
    bundle: 'observability:bundle',
  },
  runtime: {
    event: 'runtime:event',
  },
} as const;

type ValueOf<T> = T[keyof T];
type NestedValueOf<T> = T extends string ? T : ValueOf<{ [K in keyof T]: NestedValueOf<T[K]> }>;

export type IpcChannel = NestedValueOf<typeof IPC_CHANNELS>;

const ALL_IPC_CHANNELS = [
  IPC_CHANNELS.settingsRecovery.get,
  IPC_CHANNELS.settingsRecovery.openDirectory,
  IPC_CHANNELS.settingsRecovery.restart,
  IPC_CHANNELS.window.minimize,
  IPC_CHANNELS.window.toggleMaximize,
  IPC_CHANNELS.window.close,
  IPC_CHANNELS.applicationUpdate.snapshotGet,
  IPC_CHANNELS.applicationUpdate.check,
  IPC_CHANNELS.applicationUpdate.automaticChecksSet,
  IPC_CHANNELS.applicationUpdate.download,
  IPC_CHANNELS.applicationUpdate.restartAndInstall,
  IPC_CHANNELS.applicationUpdate.releasePageOpen,
  IPC_CHANNELS.applicationUpdate.snapshotChanged,
  IPC_CHANNELS.settings.changed,
  IPC_CHANNELS.settings.read,
  IPC_CHANNELS.settings.update,
  IPC_CHANNELS.credentials.read,
  IPC_CHANNELS.credentials.update,
  IPC_CHANNELS.models.getCatalog,
  IPC_CHANNELS.tools.list,
  IPC_CHANNELS.session.inputSuggestions,
  IPC_CHANNELS.session.sessionCreate,
  IPC_CHANNELS.session.sessionModelSelection,
  IPC_CHANNELS.session.sessionList,
  IPC_CHANNELS.session.sessionMessageList,
  IPC_CHANNELS.session.sessionMessageSend,
  IPC_CHANNELS.session.sessionMessagePresentation,
  IPC_CHANNELS.session.sessionMessageCancel,
  IPC_CHANNELS.session.sessionRead,
  IPC_CHANNELS.session.committedRunRead,
  IPC_CHANNELS.session.sessionContextUsageGet,
  IPC_CHANNELS.session.inputCapabilitiesGet,
  IPC_CHANNELS.session.imageInputSelect,
  IPC_CHANNELS.session.documentInputSelect,
  IPC_CHANNELS.session.imageInputClipboardRead,
  IPC_CHANNELS.session.attachmentImageRead,
  IPC_CHANNELS.session.attachmentFileStatus,
  IPC_CHANNELS.session.branchDraftCreate,
  IPC_CHANNELS.session.branchDraftCancel,
  IPC_CHANNELS.skill.list,
  IPC_CHANNELS.skill.get,
  IPC_CHANNELS.skill.enable,
  IPC_CHANNELS.skill.disable,
  IPC_CHANNELS.skill.delete,
  IPC_CHANNELS.skill.refresh,
  IPC_CHANNELS.approval.resolve,
  IPC_CHANNELS.discovery.interestList,
  IPC_CHANNELS.discovery.interestChange,
  IPC_CHANNELS.discovery.configurationGet,
  IPC_CHANNELS.discovery.configurationUpdate,
  IPC_CHANNELS.discovery.candidateSupplyConfirm,
  IPC_CHANNELS.voice.snapshot,
  IPC_CHANNELS.voice.modelStatus,
  IPC_CHANNELS.voice.modelCapability,
  IPC_CHANNELS.voice.modelsCheckUpdates,
  IPC_CHANNELS.voice.modelsPrepare,
  IPC_CHANNELS.voice.modelsCancel,
  IPC_CHANNELS.voice.sessionStart,
  IPC_CHANNELS.voice.sessionManualStart,
  IPC_CHANNELS.voice.sessionManualFinish,
  IPC_CHANNELS.voice.sessionMute,
  IPC_CHANNELS.voice.sessionEnd,
  IPC_CHANNELS.voice.speechOutputStop,
  IPC_CHANNELS.voice.speechOutputEvent,
  IPC_CHANNELS.character.show,
  IPC_CHANNELS.character.hide,
  IPC_CHANNELS.character.snapshot,
  IPC_CHANNELS.character.snapshotChanged,
  IPC_CHANNELS.character.toggleAlwaysOnTop,
  IPC_CHANNELS.character.setScale,
  IPC_CHANNELS.character.setShape,
  IPC_CHANNELS.character.moveTo,
  IPC_CHANNELS.character.openSettings,
  IPC_CHANNELS.character.showMainWindow,
  IPC_CHANNELS.character.settingsRequested,
  IPC_CHANNELS.character.selectSession,
  IPC_CHANNELS.workspace.projectList,
  IPC_CHANNELS.workspace.projectUseExisting,
  IPC_CHANNELS.workspace.projectOpen,
  IPC_CHANNELS.workspace.projectRemove,
  IPC_CHANNELS.workspace.filesList,
  IPC_CHANNELS.workspace.filesOpen,
  IPC_CHANNELS.observability.list,
  IPC_CHANNELS.observability.get,
  IPC_CHANNELS.observability.content,
  IPC_CHANNELS.observability.health,
  IPC_CHANNELS.observability.rebuildIndex,
  IPC_CHANNELS.observability.bundle,
  IPC_CHANNELS.runtime.event,
] as const;

export function isIpcChannel(value: string): value is IpcChannel {
  return (ALL_IPC_CHANNELS as readonly string[]).includes(value);
}
