// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANTHROPIC_CLASSIFIER_MODELS, ANTHROPIC_IMAGE_MODELS, ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { DEEPSEEK_CLASSIFIER_MODELS, DEEPSEEK_IMAGE_MODELS, DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { KIMI_CODING_CLASSIFIER_MODELS, KIMI_CODING_IMAGE_MODELS, KIMI_CODING_MODELS } from "./providers/kimi-coding.models.ts";
import { MINIMAX_CLASSIFIER_MODELS, MINIMAX_IMAGE_MODELS, MINIMAX_MODELS } from "./providers/minimax.models.ts";
import { MINIMAX_CN_CLASSIFIER_MODELS, MINIMAX_CN_IMAGE_MODELS, MINIMAX_CN_MODELS } from "./providers/minimax-cn.models.ts";
import { MOONSHOTAI_CLASSIFIER_MODELS, MOONSHOTAI_IMAGE_MODELS, MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { MOONSHOTAI_CN_CLASSIFIER_MODELS, MOONSHOTAI_CN_IMAGE_MODELS, MOONSHOTAI_CN_MODELS } from "./providers/moonshotai-cn.models.ts";
import { OPENAI_CLASSIFIER_MODELS, OPENAI_IMAGE_MODELS, OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENAI_CODEX_CLASSIFIER_MODELS, OPENAI_CODEX_IMAGE_MODELS, OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.ts";
import { ZAI_CLASSIFIER_MODELS, ZAI_IMAGE_MODELS, ZAI_MODELS } from "./providers/zai.models.ts";
import { ZAI_CODING_CN_CLASSIFIER_MODELS, ZAI_CODING_CN_IMAGE_MODELS, ZAI_CODING_CN_MODELS } from "./providers/zai-coding-cn.models.ts";

export const MODELS: {
	readonly "anthropic": typeof ANTHROPIC_MODELS;
	readonly "deepseek": typeof DEEPSEEK_MODELS;
	readonly "kimi-coding": typeof KIMI_CODING_MODELS;
	readonly "minimax": typeof MINIMAX_MODELS;
	readonly "minimax-cn": typeof MINIMAX_CN_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_MODELS;
	readonly "moonshotai-cn": typeof MOONSHOTAI_CN_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "openai-codex": typeof OPENAI_CODEX_MODELS;
	readonly "zai": typeof ZAI_MODELS;
	readonly "zai-coding-cn": typeof ZAI_CODING_CN_MODELS;
} = {
	"anthropic": ANTHROPIC_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"kimi-coding": KIMI_CODING_MODELS,
	"minimax": MINIMAX_MODELS,
	"minimax-cn": MINIMAX_CN_MODELS,
	"moonshotai": MOONSHOTAI_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_MODELS,
	"openai": OPENAI_MODELS,
	"openai-codex": OPENAI_CODEX_MODELS,
	"zai": ZAI_MODELS,
	"zai-coding-cn": ZAI_CODING_CN_MODELS,
};

export const IMAGE_MODELS: {
	readonly "anthropic": typeof ANTHROPIC_IMAGE_MODELS;
	readonly "deepseek": typeof DEEPSEEK_IMAGE_MODELS;
	readonly "kimi-coding": typeof KIMI_CODING_IMAGE_MODELS;
	readonly "minimax": typeof MINIMAX_IMAGE_MODELS;
	readonly "minimax-cn": typeof MINIMAX_CN_IMAGE_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_IMAGE_MODELS;
	readonly "moonshotai-cn": typeof MOONSHOTAI_CN_IMAGE_MODELS;
	readonly "openai": typeof OPENAI_IMAGE_MODELS;
	readonly "openai-codex": typeof OPENAI_CODEX_IMAGE_MODELS;
	readonly "zai": typeof ZAI_IMAGE_MODELS;
	readonly "zai-coding-cn": typeof ZAI_CODING_CN_IMAGE_MODELS;
} = {
	"anthropic": ANTHROPIC_IMAGE_MODELS,
	"deepseek": DEEPSEEK_IMAGE_MODELS,
	"kimi-coding": KIMI_CODING_IMAGE_MODELS,
	"minimax": MINIMAX_IMAGE_MODELS,
	"minimax-cn": MINIMAX_CN_IMAGE_MODELS,
	"moonshotai": MOONSHOTAI_IMAGE_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_IMAGE_MODELS,
	"openai": OPENAI_IMAGE_MODELS,
	"openai-codex": OPENAI_CODEX_IMAGE_MODELS,
	"zai": ZAI_IMAGE_MODELS,
	"zai-coding-cn": ZAI_CODING_CN_IMAGE_MODELS,
};

export const CLASSIFIER_MODELS: {
	readonly "anthropic": typeof ANTHROPIC_CLASSIFIER_MODELS;
	readonly "deepseek": typeof DEEPSEEK_CLASSIFIER_MODELS;
	readonly "kimi-coding": typeof KIMI_CODING_CLASSIFIER_MODELS;
	readonly "minimax": typeof MINIMAX_CLASSIFIER_MODELS;
	readonly "minimax-cn": typeof MINIMAX_CN_CLASSIFIER_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_CLASSIFIER_MODELS;
	readonly "moonshotai-cn": typeof MOONSHOTAI_CN_CLASSIFIER_MODELS;
	readonly "openai": typeof OPENAI_CLASSIFIER_MODELS;
	readonly "openai-codex": typeof OPENAI_CODEX_CLASSIFIER_MODELS;
	readonly "zai": typeof ZAI_CLASSIFIER_MODELS;
	readonly "zai-coding-cn": typeof ZAI_CODING_CN_CLASSIFIER_MODELS;
} = {
	"anthropic": ANTHROPIC_CLASSIFIER_MODELS,
	"deepseek": DEEPSEEK_CLASSIFIER_MODELS,
	"kimi-coding": KIMI_CODING_CLASSIFIER_MODELS,
	"minimax": MINIMAX_CLASSIFIER_MODELS,
	"minimax-cn": MINIMAX_CN_CLASSIFIER_MODELS,
	"moonshotai": MOONSHOTAI_CLASSIFIER_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_CLASSIFIER_MODELS,
	"openai": OPENAI_CLASSIFIER_MODELS,
	"openai-codex": OPENAI_CODEX_CLASSIFIER_MODELS,
	"zai": ZAI_CLASSIFIER_MODELS,
	"zai-coding-cn": ZAI_CODING_CN_CLASSIFIER_MODELS,
};
