// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import { ANTHROPIC_MODELS } from "./providers/anthropic.models.ts";
import { DEEPSEEK_MODELS } from "./providers/deepseek.models.ts";
import { GOOGLE_MODELS } from "./providers/google.models.ts";
import { HUGGINGFACE_MODELS } from "./providers/huggingface.models.ts";
import { MINIMAX_MODELS } from "./providers/minimax.models.ts";
import { MINIMAX_CN_MODELS } from "./providers/minimax-cn.models.ts";
import { MOONSHOTAI_MODELS } from "./providers/moonshotai.models.ts";
import { MOONSHOTAI_CN_MODELS } from "./providers/moonshotai-cn.models.ts";
import { OPENAI_MODELS } from "./providers/openai.models.ts";
import { OPENAI_CODEX_MODELS } from "./providers/openai-codex.models.ts";
import { OPENROUTER_MODELS } from "./providers/openrouter.models.ts";
import { QWEN_TOKEN_PLAN_MODELS } from "./providers/qwen-token-plan.models.ts";
import { QWEN_TOKEN_PLAN_CN_MODELS } from "./providers/qwen-token-plan-cn.models.ts";

export const MODELS: {
	readonly "anthropic": typeof ANTHROPIC_MODELS;
	readonly "deepseek": typeof DEEPSEEK_MODELS;
	readonly "google": typeof GOOGLE_MODELS;
	readonly "huggingface": typeof HUGGINGFACE_MODELS;
	readonly "minimax": typeof MINIMAX_MODELS;
	readonly "minimax-cn": typeof MINIMAX_CN_MODELS;
	readonly "moonshotai": typeof MOONSHOTAI_MODELS;
	readonly "moonshotai-cn": typeof MOONSHOTAI_CN_MODELS;
	readonly "openai": typeof OPENAI_MODELS;
	readonly "openai-codex": typeof OPENAI_CODEX_MODELS;
	readonly "openrouter": typeof OPENROUTER_MODELS;
	readonly "qwen-token-plan": typeof QWEN_TOKEN_PLAN_MODELS;
	readonly "qwen-token-plan-cn": typeof QWEN_TOKEN_PLAN_CN_MODELS;
} = {
	"anthropic": ANTHROPIC_MODELS,
	"deepseek": DEEPSEEK_MODELS,
	"google": GOOGLE_MODELS,
	"huggingface": HUGGINGFACE_MODELS,
	"minimax": MINIMAX_MODELS,
	"minimax-cn": MINIMAX_CN_MODELS,
	"moonshotai": MOONSHOTAI_MODELS,
	"moonshotai-cn": MOONSHOTAI_CN_MODELS,
	"openai": OPENAI_MODELS,
	"openai-codex": OPENAI_CODEX_MODELS,
	"openrouter": OPENROUTER_MODELS,
	"qwen-token-plan": QWEN_TOKEN_PLAN_MODELS,
	"qwen-token-plan-cn": QWEN_TOKEN_PLAN_CN_MODELS,
};
