"""Public configuration API for the Python AI layer; importing performs no I/O."""

from app.ai.api.transform import transform_messages
from app.ai.assistant_message_frames import (
    AssistantMessageFrame,
    AssistantMessageFrameEncoder,
    reduce_assistant_message_frames,
)
from app.ai.auth.memory import InMemoryCredentialStore
from app.ai.auth.types import ApiKeyCredential, AuthOverride, CredentialStore, ResolvedAuth
from app.ai.codec import decode_messages, encode_messages
from app.ai.context_budget import (
    ContextUsageEstimate,
    adjust_max_tokens_for_thinking,
    calculate_context_tokens,
    clamp_max_tokens_to_context,
    estimate_context_tokens,
    estimate_message_tokens,
    estimate_text_tokens,
    is_context_overflow,
    is_recoverable_length,
)
from app.ai.errors import (
    AuthError,
    ConfigurationError,
    FrameSequenceError,
    LifecycleError,
    MessageDecodeError,
    StrictSchemaError,
    ToolValidationError,
)
from app.ai.events import AssistantMessageEvent
from app.ai.messages import (
    AssistantContent,
    AssistantMessage,
    Context,
    ImageContent,
    InputContent,
    JsonSchemaSampling,
    JSONValue,
    Message,
    StopReason,
    SystemMessage,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolDefinition,
    ToolResultMessage,
    Transcript,
    Usage,
    UsageCost,
    UserMessage,
)
from app.ai.model import (
    CatalogSource,
    Model,
    ModelCapabilities,
    ModelCompat,
    Pricing,
    PricingTier,
    clamp_thinking_level,
    get_supported_thinking_levels,
)
from app.ai.models import Models, create_models
from app.ai.options import CallOptions, ProviderResponse, RetryCallbacks, RetryPolicy, SimpleOptions
from app.ai.provider import Provider
from app.ai.providers.deepseek import deepseek_provider
from app.ai.providers.openai import openai_provider
from app.ai.runtime.retry import (
    is_retryable_assistant_error,
    retry_assistant_call,
    retry_provider_request,
)
from app.ai.stream import AssistantResponse
from app.ai.tools.arguments import (
    parse_partial_arguments,
    validate_tool_arguments,
    validate_tool_call,
)
from app.ai.tools.schema import make_strict_json_schema, resolve_json_schema_strict_sampling
from app.ai.transcript import (
    declarations_equal,
    get_current_system_message,
    get_current_system_prompt,
    get_current_tools,
    get_initial_system_message,
    get_system_message_text,
    get_tool_state_changes,
    normalize_context,
    render_system_message_update,
    resolve_transcript,
    resolve_transcript_tools,
    to_tool_declaration,
    without_initial_system_message,
)
from app.ai.usage import calculate_usage_cost

__all__ = [
    "ApiKeyCredential",
    "AssistantContent",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageFrame",
    "AssistantMessageFrameEncoder",
    "AssistantResponse",
    "AuthError",
    "AuthOverride",
    "CallOptions",
    "CatalogSource",
    "ConfigurationError",
    "Context",
    "ContextUsageEstimate",
    "CredentialStore",
    "FrameSequenceError",
    "ImageContent",
    "InMemoryCredentialStore",
    "InputContent",
    "JSONValue",
    "JsonSchemaSampling",
    "LifecycleError",
    "Message",
    "MessageDecodeError",
    "Model",
    "ModelCapabilities",
    "ModelCompat",
    "Models",
    "Pricing",
    "PricingTier",
    "Provider",
    "ProviderResponse",
    "ResolvedAuth",
    "RetryCallbacks",
    "RetryPolicy",
    "SimpleOptions",
    "StopReason",
    "StrictSchemaError",
    "SystemMessage",
    "TextContent",
    "ThinkingContent",
    "ToolCall",
    "ToolDefinition",
    "ToolResultMessage",
    "ToolValidationError",
    "Transcript",
    "Usage",
    "UsageCost",
    "UserMessage",
    "adjust_max_tokens_for_thinking",
    "calculate_context_tokens",
    "calculate_usage_cost",
    "clamp_max_tokens_to_context",
    "clamp_thinking_level",
    "create_models",
    "declarations_equal",
    "decode_messages",
    "deepseek_provider",
    "encode_messages",
    "estimate_context_tokens",
    "estimate_message_tokens",
    "estimate_text_tokens",
    "get_current_system_message",
    "get_current_system_prompt",
    "get_current_tools",
    "get_initial_system_message",
    "get_supported_thinking_levels",
    "get_system_message_text",
    "get_tool_state_changes",
    "is_context_overflow",
    "is_recoverable_length",
    "is_retryable_assistant_error",
    "make_strict_json_schema",
    "normalize_context",
    "openai_provider",
    "parse_partial_arguments",
    "reduce_assistant_message_frames",
    "render_system_message_update",
    "resolve_json_schema_strict_sampling",
    "resolve_transcript",
    "resolve_transcript_tools",
    "retry_assistant_call",
    "retry_provider_request",
    "to_tool_declaration",
    "transform_messages",
    "validate_tool_arguments",
    "validate_tool_call",
    "without_initial_system_message",
]
