/*
 * Renderer-safe public Product Host Interface exports.
 * Concrete composition roots consume these contracts through the public entry.
 */
export { EventSchema as RuntimeEventSchema } from '@megumi/events';
export { redactHostRuntimeValue } from './runtime-redaction';
export type { AnyEvent } from '@megumi/events';

export * from './product-host';
export * from './discovery-host';
export type {
  WorkspaceFileEntryUiDto,
  WorkspaceListFilesUiResult,
  WorkspaceListProjectsUiResult,
  WorkspaceOpenFileUiResult,
  WorkspaceOpenProjectUiResult,
  WorkspaceProjectUiDto,
  WorkspaceRemoveProjectUiResult,
  WorkspaceUseExistingProjectUiResult,
} from './workspace-host';
export type { WorkspaceHost } from './workspace-host';
export type { DirectoryPicker, DirectoryPickerResult } from './capabilities/directory-picker';
export type { FileOpener, FileOpenResult } from './capabilities/file-opener';
export type {
  CancelBranchDraftResult,
  CancelUserInputResult,
  CancelUserInputPayload,
  CreateBranchDraftResult,
  CreateSessionResult,
  GetInputSuggestionsResult,
  GetContextUsageResult,
  ReadSessionRequest,
  ReadSessionResult,
  ReadCommittedRunRequest,
  ReadCommittedRunResult,
  SessionHost,
  ListUserMessagesByExecutionIdsResult,
  ListSessionsResult,
  RunDto,
  SendUserInputPayload,
  SendUserInputRequest,
  SendUserInputResult,
  SessionDto,
  SessionConversationItemDto,
  SessionMessageConversationItemDto,
  SessionMessageDto,
  SessionBranchConversationItemDto,
  UserMessageDto,
  WorkspaceChangeSummaryDto,
  SessionReadDiagnosticDto,
  SessionRuntimeEventRangeDto,
  UserMessageSummaryDto,
  InputSuggestionQueryItem,
  InputSuggestionQueryResult,
  PermissionMode,
  SelectedImageDto,
  SelectedDocumentDto,
  InputCapabilitiesResult,
  SelectImagesResult,
  SelectDocumentsResult,
  ReadAttachmentImageRequest,
  ReadAttachmentImageResult,
  GetAttachmentFileStatusRequest,
  GetAttachmentFileStatusResult,
} from './session-host';
export type { AttachmentPicker } from './capabilities/attachment-picker';
export type { LocalFileAvailability } from './capabilities/local-file-availability';
export type { ProductWorkspaceFileSystem } from './capabilities/workspace-file-system';
export type {
  DisableSkillUiResponse,
  DeleteSkillUiResponse,
  EnableSkillUiResponse,
  GetSkillDetailUiResponse,
  ListSkillsUiResponse,
  RefreshSkillsUiResponse,
  SkillDetailUiDto,
  SkillHost,
  SkillListUiItem,
} from './skill-host';
export type {
  AppLanguage,
  AppThemeName,
  EmptyUiResult,
  CredentialValueUiResult,
  ModelCapabilitiesUiDto,
  ModelSupportLevelUi,
  ProviderModelSettingsUiDto,
  ProviderCatalogUiDto,
  ProviderListUiResult,
  ProviderPublicStatusUiDto,
  PermissionRuleEffectUi,
  PermissionRuleUiDto,
  PermissionRuleChangeUi,
  PermissionRuleCatalogUiDto,
  SettingsCompleteSetupUiResult,
  SettingsCompleteSetupPayload,
  SettingsData,
  SettingsGetPayload,
  SettingsGetUiResult,
  SettingsUiResolved,
  SettingsUpdatePayload,
  SettingsUpdateUiResult,
  VoiceTtsApiKeyUiRequest,
  VoiceTtsKeyUiResult,
  VoiceTtsPublicUiDto,
  DiscoverySourceCredentialStatusUiRequest,
  DiscoverySourceCredentialSetUiRequest,
  DiscoverySourceCredentialStatusUiResult,
} from './settings-host';
export type { SettingsHost } from './settings-host';
export type {
  ApprovalHost,
  ApprovalHostResult,
  ApprovalResolvePayload,
} from './approval-host';
export type { ObservabilityHost } from './observability-host';
export type {
  VoiceHost,
  VoiceHostModelStatus,
  VoiceHostModelUpdateResult,
  VoiceHostMutationResult,
  VoiceHostSnapshot,
  VoiceSessionMutedPayload,
  VoiceSessionStartPayload,
  VoiceModelCapabilityPayload,
  VoiceHostModelCapabilityStatus,
} from './voice-host';
export {
  VoiceEmptyPayloadSchema,
  VoiceModelStatusResultSchema,
  VoiceModelCapabilityPayloadSchema,
  VoiceModelCapabilityStatusSchema,
  VoiceModelUpdateResultSchema,
  VoiceHostMutationResultSchema,
  VoiceSessionMutedPayloadSchema,
  VoiceSessionStartPayloadSchema,
  VoiceSnapshotSchema,
} from './voice-host';
export type { DiagnosticBundleSaver } from './capabilities/diagnostic-bundle-saver';
export type {
  DiagnosticBundleDto,
  DiagnosticBundleFileDto,
  ObservabilityContentCheckpointUiDto,
  ObservabilityCorrelationUiDto,
  ObservabilityDiagnosticErrorUiDto,
  ObservabilityEventUiDto,
  ObservabilityExportResult,
  ObservabilityGetContentResult,
  ObservabilityGetTraceResult,
  ObservabilityHealthResult,
  ObservabilityHealthUiDto,
  ObservabilityListResult,
  ObservabilityRebuildResult,
  ObservabilitySpanUiDto,
  ObservabilityTraceDetailUiDto,
  ObservabilityTraceSummaryUiDto,
} from './observability-host';
export {
  ObservabilityContentPayloadSchema,
  ObservabilityCorrelationSchema,
  ObservabilityEmptyPayloadSchema,
  ObservabilityExportResultSchema,
  ObservabilityGetContentResultSchema,
  ObservabilityGetTraceResultSchema,
  ObservabilityHealthResultSchema,
  ObservabilityListPayloadSchema,
  ObservabilityListResultSchema,
  ObservabilityRebuildResultSchema,
  ObservabilityTracePayloadSchema,
} from './observability-host';
export {
  WorkspaceListProjectsPayloadSchema,
  WorkspaceUseExistingProjectPayloadSchema,
  ProjectOpenPayloadSchema,
  ProjectRemovePayloadSchema,
  WorkspaceFilesListPayloadSchema,
  WorkspaceFileOpenPayloadSchema,
  WorkspaceListProjectsUiResultSchema,
  WorkspaceUseExistingProjectUiResultSchema,
  WorkspaceOpenProjectUiResultSchema,
  WorkspaceRemoveProjectUiResultSchema,
  WorkspaceListFilesUiResultSchema,
  WorkspaceOpenFileUiResultSchema,
} from './workspace-host';
export {
  InputSuggestionsPayloadSchema,
  SessionCreatePayloadSchema,
  SessionListPayloadSchema,
  SessionMessageListPayloadSchema,
  SessionReadPayloadSchema,
  CommittedRunReadPayloadSchema,
  SessionContextUsageGetPayloadSchema,
  SessionMessageSendPayloadSchema,
  SessionMessageCancelPayloadSchema,
  SessionBranchDraftCreatePayloadSchema,
  SessionBranchDraftCancelPayloadSchema,
  InputCapabilitiesPayloadSchema,
  ImageInputSelectPayloadSchema,
  DocumentInputSelectPayloadSchema,
  ImageInputClipboardReadPayloadSchema,
  AttachmentImageReadPayloadSchema,
  AttachmentFileStatusPayloadSchema,
  InputCapabilitiesResultSchema,
  SelectImagesResultSchema,
  SelectDocumentsResultSchema,
  ReadAttachmentImageResultSchema,
  AttachmentFileStatusResultSchema,
  SendUserInputPayloadSchema,
  GetInputSuggestionsResultSchema,
  CreateSessionResultSchema,
  ListSessionsResultSchema,
  ListUserMessagesByExecutionIdsResultSchema,
  CancelUserInputPayloadSchema,
  CreateBranchDraftPayloadSchema,
  CancelBranchDraftPayloadSchema,
  GetContextUsageResultSchema,
  ReadSessionResultSchema,
  ReadCommittedRunResultSchema,
  SessionDtoSchema,
  RunDtoSchema,
  UserMessageDtoSchema,
  SessionMessageDtoSchema,
  SessionMessageConversationItemDtoSchema,
  SessionConversationItemDtoSchema,
  SessionBranchConversationItemDtoSchema,
  WorkspaceChangeSummaryDtoSchema,
} from './session-host';
export {
  SkillListPayloadSchema,
  SkillGetPayloadSchema,
  SkillEnablePayloadSchema,
  SkillDisablePayloadSchema,
  SkillDeletePayloadSchema,
  SkillRefreshPayloadSchema,
  ListSkillsUiResponseSchema,
  GetSkillDetailUiResponseSchema,
  EnableSkillUiResponseSchema,
  DisableSkillUiResponseSchema,
  DeleteSkillUiResponseSchema,
  RefreshSkillsUiResponseSchema,
} from './skill-host';
export {
  SettingsGetPayloadSchema,
  SettingsUpdatePayloadSchema,
  SettingsCompleteSetupPayloadSchema,
  ProviderListPayloadSchema,
  ProviderUpdatePayloadSchema,
  ProviderDeletePayloadSchema,
  ProviderApiKeyPayloadSchema,
  ProviderDeleteApiKeyPayloadSchema,
  VoiceTtsApiKeyPayloadSchema,
  VoiceTtsPublicUiDtoSchema,
  VoiceTtsKeyUiResultSchema,
  DiscoverySourceCredentialStatusPayloadSchema,
  DiscoverySourceCredentialSetPayloadSchema,
  DiscoverySourceCredentialStatusUiResultSchema,
  SettingsGetUiResultSchema,
  SettingsUpdateUiResultSchema,
  SettingsCompleteSetupUiResultSchema,
  ProviderListUiResultSchema,
  EmptyUiResultSchema,
  CredentialValueUiResultSchema,
} from './settings-host';
export { ApprovalResolvePayloadSchema, ApprovalResolveResultSchema } from './approval-host';
