export type ThemeName =
  | 'megumi-warm'
  | 'neutral-light'
  | 'sunlit-sky'
  | 'rose-moon'
  | 'verdant-cloud'
  | 'cangming-blue'
  | 'frost-cyan'
  | 'cyan-tide'
  | 'midnight-blue';

export const SEMANTIC_THEME_VARIABLES = [
  '--color-app-bg',
  '--color-surface',
  '--color-surface-muted',
  '--color-surface-elevated',
  '--color-border',
  '--color-border-strong',
  '--color-text',
  '--color-text-muted',
  '--color-text-subtle',
  '--color-accent',
  '--color-accent-soft',
  '--color-accent-foreground',
  '--color-danger',
  '--color-danger-soft',
  '--color-warning',
  '--color-warning-soft',
  '--color-success',
  '--color-success-soft',
  '--color-approval',
  '--color-approval-soft',
  '--color-focus',
  '--shadow-soft',
] as const;

export type SemanticThemeVariable = (typeof SEMANTIC_THEME_VARIABLES)[number];

export type ThemeVariables = Record<SemanticThemeVariable, string>;

export interface ThemeDefinition {
  name: ThemeName;
  variables: ThemeVariables;
}

export const themeDefinitions = {
  'megumi-warm': {
    name: 'megumi-warm',
    variables: {
      '--color-app-bg': '#f7f3ea',
      '--color-surface': '#fffaf0',
      '--color-surface-muted': '#eee8dd',
      '--color-surface-elevated': '#fffdf7',
      '--color-border': '#ded6c8',
      '--color-border-strong': '#c9bdad',
      '--color-text': '#2f2a24',
      '--color-text-muted': '#81776b',
      '--color-text-subtle': '#aaa096',
      '--color-accent': '#5f8ea1',
      '--color-accent-soft': '#d9e9ec',
      '--color-accent-foreground': '#f8fcfd',
      '--color-danger': '#b45a4f',
      '--color-danger-soft': '#f3ded9',
      '--color-warning': '#a87832',
      '--color-warning-soft': '#f4e6c8',
      '--color-success': '#5f8a68',
      '--color-success-soft': '#dcebdd',
      '--color-approval': '#7d6ea8',
      '--color-approval-soft': '#e9e2f3',
      '--color-focus': '#7aa9b9',
      '--shadow-soft': '0 16px 40px rgba(68, 55, 36, 0.12)',
    },
  },
  'neutral-light': {
    name: 'neutral-light',
    variables: {
      '--color-app-bg': '#f7f7f5',
      '--color-surface': '#ffffff',
      '--color-surface-muted': '#eeeeec',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#d8d8d4',
      '--color-border-strong': '#bfc0ba',
      '--color-text': '#272722',
      '--color-text-muted': '#73736c',
      '--color-text-subtle': '#a1a19a',
      '--color-accent': '#56616f',
      '--color-accent-soft': '#e5e8ec',
      '--color-accent-foreground': '#ffffff',
      '--color-danger': '#ad514b',
      '--color-danger-soft': '#f1dcda',
      '--color-warning': '#9a7338',
      '--color-warning-soft': '#efe4cf',
      '--color-success': '#587d60',
      '--color-success-soft': '#dfe9e0',
      '--color-approval': '#6f668a',
      '--color-approval-soft': '#e7e4ef',
      '--color-focus': '#7d8794',
      '--shadow-soft': '0 16px 40px rgba(30, 31, 28, 0.1)',
    },
  },
  'sunlit-sky': {
    name: 'sunlit-sky',
    variables: {
      '--color-app-bg': '#fff9e6',
      '--color-surface': '#fffdf5',
      '--color-surface-muted': '#f4dc84',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#e4d7a1',
      '--color-border-strong': '#c4ae55',
      '--color-text': '#2d2b24',
      '--color-text-muted': '#6e6755',
      '--color-text-subtle': '#91866c',
      '--color-accent': '#79bedf',
      '--color-accent-soft': '#dceff7',
      '--color-accent-foreground': '#17333d',
      '--color-danger': '#a8474b',
      '--color-danger-soft': '#f5ddde',
      '--color-warning': '#856515',
      '--color-warning-soft': '#f7e7ae',
      '--color-success': '#4f7849',
      '--color-success-soft': '#dfecd9',
      '--color-approval': '#675b8e',
      '--color-approval-soft': '#e8e2f1',
      '--color-focus': '#367f9f',
      '--shadow-soft': '0 16px 40px rgba(91, 78, 32, 0.14)',
    },
  },
  'rose-moon': {
    name: 'rose-moon',
    variables: {
      '--color-app-bg': '#f8f4f5',
      '--color-surface': '#fffafa',
      '--color-surface-muted': '#e8f0f2',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#ddcfd2',
      '--color-border-strong': '#c3a5ab',
      '--color-text': '#33272a',
      '--color-text-muted': '#735f64',
      '--color-text-subtle': '#9d898e',
      '--color-accent': '#d87888',
      '--color-accent-soft': '#f6e0e4',
      '--color-accent-foreground': '#3d171e',
      '--color-danger': '#a8474b',
      '--color-danger-soft': '#f5ddde',
      '--color-warning': '#85651c',
      '--color-warning-soft': '#f3e7c9',
      '--color-success': '#527b57',
      '--color-success-soft': '#dcebdd',
      '--color-approval': '#675b8e',
      '--color-approval-soft': '#e8e2f1',
      '--color-focus': '#a94b5d',
      '--shadow-soft': '0 16px 40px rgba(91, 48, 57, 0.13)',
    },
  },
  'verdant-cloud': {
    name: 'verdant-cloud',
    variables: {
      '--color-app-bg': '#fbf1d7',
      '--color-surface': '#fffaf0',
      '--color-surface-muted': '#dce8c9',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#d8d1b4',
      '--color-border-strong': '#aeb68f',
      '--color-text': '#273022',
      '--color-text-muted': '#626c58',
      '--color-text-subtle': '#89927c',
      '--color-accent': '#73ae52',
      '--color-accent-soft': '#deedcf',
      '--color-accent-foreground': '#18300e',
      '--color-danger': '#a84f49',
      '--color-danger-soft': '#f4dfdb',
      '--color-warning': '#84651c',
      '--color-warning-soft': '#f3e4ba',
      '--color-success': '#47783d',
      '--color-success-soft': '#dcebd6',
      '--color-approval': '#665d8c',
      '--color-approval-soft': '#e6e2ef',
      '--color-focus': '#4c8631',
      '--shadow-soft': '0 16px 40px rgba(62, 77, 38, 0.14)',
    },
  },
  'cangming-blue': {
    name: 'cangming-blue',
    variables: {
      '--color-app-bg': '#faf2e0',
      '--color-surface': '#fffaf4',
      '--color-surface-muted': '#e3ecf1',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#d9d2c1',
      '--color-border-strong': '#b8b09e',
      '--color-text': '#242d35',
      '--color-text-muted': '#5f6973',
      '--color-text-subtle': '#8c958f',
      '--color-accent': '#0e61ac',
      '--color-accent-soft': '#dceaf7',
      '--color-accent-foreground': '#ffffff',
      '--color-danger': '#a94d49',
      '--color-danger-soft': '#f3dedb',
      '--color-warning': '#86661d',
      '--color-warning-soft': '#f2e6c6',
      '--color-success': '#4d7854',
      '--color-success-soft': '#dce9dd',
      '--color-approval': '#655d8e',
      '--color-approval-soft': '#e5e2f0',
      '--color-focus': '#0e61ac',
      '--shadow-soft': '0 16px 42px rgba(33, 61, 83, 0.14)',
    },
  },
  'frost-cyan': {
    name: 'frost-cyan',
    variables: {
      '--color-app-bg': '#fcf9e8',
      '--color-surface': '#fffef6',
      '--color-surface-muted': '#def0ed',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#cddfd9',
      '--color-border-strong': '#9dbeb7',
      '--color-text': '#243030',
      '--color-text-muted': '#5b6d6b',
      '--color-text-subtle': '#879794',
      '--color-accent': '#00b7c7',
      '--color-accent-soft': '#d5f3f5',
      '--color-accent-foreground': '#07383c',
      '--color-danger': '#a94d49',
      '--color-danger-soft': '#f3dedb',
      '--color-warning': '#86661d',
      '--color-warning-soft': '#f2e6c6',
      '--color-success': '#44796a',
      '--color-success-soft': '#d8ebe4',
      '--color-approval': '#655d8e',
      '--color-approval-soft': '#e5e2f0',
      '--color-focus': '#007e89',
      '--shadow-soft': '0 16px 42px rgba(31, 79, 76, 0.13)',
    },
  },
  'cyan-tide': {
    name: 'cyan-tide',
    variables: {
      '--color-app-bg': '#e8f4f0',
      '--color-surface': '#f8fcfa',
      '--color-surface-muted': '#b1d5c9',
      '--color-surface-elevated': '#ffffff',
      '--color-border': '#b9d2ca',
      '--color-border-strong': '#82afa2',
      '--color-text': '#20302d',
      '--color-text-muted': '#566b65',
      '--color-text-subtle': '#7f938d',
      '--color-accent': '#00b7c7',
      '--color-accent-soft': '#ccf0f1',
      '--color-accent-foreground': '#07383c',
      '--color-danger': '#a94d49',
      '--color-danger-soft': '#f3dedb',
      '--color-warning': '#82631c',
      '--color-warning-soft': '#f0e5c5',
      '--color-success': '#3f7465',
      '--color-success-soft': '#d4e8e0',
      '--color-approval': '#655d8e',
      '--color-approval-soft': '#e5e2f0',
      '--color-focus': '#007e89',
      '--shadow-soft': '0 16px 42px rgba(25, 78, 72, 0.14)',
    },
  },
  'midnight-blue': {
    name: 'midnight-blue',
    variables: {
      '--color-app-bg': '#10151d',
      '--color-surface': '#171d27',
      '--color-surface-muted': '#202838',
      '--color-surface-elevated': '#222a36',
      '--color-border': '#344052',
      '--color-border-strong': '#4b5a70',
      '--color-text': '#eef3f8',
      '--color-text-muted': '#aab7c4',
      '--color-text-subtle': '#7d8b9a',
      '--color-accent': '#75a9be',
      '--color-accent-soft': '#233d4a',
      '--color-accent-foreground': '#081117',
      '--color-danger': '#da8275',
      '--color-danger-soft': '#4f302d',
      '--color-warning': '#d0a85f',
      '--color-warning-soft': '#453927',
      '--color-success': '#86b989',
      '--color-success-soft': '#2d4533',
      '--color-approval': '#b1a0d8',
      '--color-approval-soft': '#3b3551',
      '--color-focus': '#87c1d8',
      '--shadow-soft': '0 18px 48px rgba(0, 0, 0, 0.36)',
    },
  },
} satisfies Record<ThemeName, ThemeDefinition>;

export const themeNames = Object.keys(themeDefinitions) as ThemeName[];

export function getThemeDefinition(theme: ThemeName): ThemeDefinition {
  return themeDefinitions[theme];
}
